### ISSUE TITLE
stem

### ISSUE THREAD

**Issue by dwhieb** [digitallinguistics/data-format#434]
For some languages, the lemma and the citation form are the same, but neither one of those is the stem. In this case, it is useful to have a separate `stem` field. (h/t @eddieantonio 🙏🏻)

**Comment by eddieantonio** [comment]
In nêhiyawêwin (`crk`):

<dl>
<dt>citation form</dt><dd>wâpamêw</dd>
<dt>stem</dt><dd>wâpam-</dd>
<dt>lemma</dt><dd>wâpamêw</dd>
</dl>

Please check with @aarppe. Note that some teachers use the stem as the citation form, but Algonquian tradition dictates that the `+Ind+3Sg+4Sg/PlO` form should be used instead.

**Comment by aarppe** [comment]
The above is correct, though what I've heard is that in some Ojibwe resources one might use the conjunct form as the citation form (since in Ojibwe conjunct doesn't require always a grammatical preverb comparable to _ê-_). Also, in the case of Cree, native speaker consultants would generally offer the conjunct form over the independent one, even if they did consider them relatively equivalent. However, a Plains Cree dictionary based on conjunct forms would not be that useful, as they would all start with _ê-_.

**Comment by dwhieb** [comment]
In the DLx format, the stem would be given in the list of forms (the `forms` field), making a separate `stem` field redundant (which explains why I never included something as obvious as the stem in the format in the first place—the form _is_ the stem; other fields are necessary because they're potentially different from the stem).

Lexeme.forms<Array:form>.transcription = stem
